name: Lint 
on: 
  push:
    branches: 
      - dev
jobs:
  run-linters:
    runs-on: ubuntu-lastest
    steps:
      - name: change directory
        run: |
          cd cv;
      - name: LaTeX linter (chktex)
        uses: j2kun/chktex-action@v1.0.2
